apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  selector:
    app: result-app
  ports:
  - name: "result-service"
    port: 8081
    targetPort: 80
    nodePort: 31001