apiVersion: v1
kind: Pod
metadata:
  name: postgres-db-pod
  labels:
    app: postgres-db
spec:
  containers:
    - name: postgres-db-container
      image: postgres:15-alpine
      ports:
        - name: postgres
          containerPort: 5432
      envFrom:
        - secretRef:
            name: postgres-db-secret
