apiVersion: v1
kind: Pod
metadata:
  name: vote-app-pod
  labels:
    app: vote-app
spec:
  containers:
  - name: vote-app-container
    image: dockersamples/examplevotingapp_vote
    ports:
    - name: vote
      containerPort: 80